### ISSUE TITLE
ERR_INVALID_ARG_TYPE "path"

### ISSUE THREAD

**Issue by marvictifora** [accimeesterlin/nodemailer-examples#12]
after doing what instructed my email fails to send and returns this error.

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at ExpressHandlebars._resolveLayoutPath (/home/marvic/Documents/email_schedule/node_modules/nodemailer-handlebars/node_modules/express-handlebars/lib/express-handlebars.js:342:17)
    at ExpressHandlebars.<anonymous> (/home/marvic/Documents/email_schedule/node_modules/nodemailer-handlebars/node_modules/express-handlebars/lib/express-handlebars.js:223:35) {
  code: 'ERR_INVALID_ARG_TYPE'

am i doing something wrong???

**Comment by PManager1** [comment]
yes same fucking issue.

**Comment by anirudhmalik** [comment]
`transporter.use('compile', hbs({`
 `   viewEngine: **{`
	`	defaultLayout: false        // <-----   added this`
	`  },`**
  `  viewPath: './views/'`
`}));`

add **defaultLayout: false**
